LMS_GL/Models/Cart.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LMS_GL.Models
{
    public class Cart
    {
        [Key]
        public int id { get; set; }
        [NotMapped]
        public IFormFile CourseImage { get; set; }
        public string ImagePath { get; set; }
        
        [ForeignKey("student")]
        public int StuId { get; set; }
        public Student student { get; set; }

        [ForeignKey("courses")]
        public int CourseId { get; set; }
        public Courses courses { get; set; }
       
        public string Coursename { get; set; }
        public string Price { get; set; }
        public string Description { get; set; }
        public string duration { get; set; }
        public string MentorName { get; set; }

    }
}

LMS_GL/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LMS_GL.Models;
using System.Text;
using System.Security.Cryptography;
using LMS_GL.Data;
using Microsoft.AspNetCore.Identity;

namespace LMS_GL.Controllers
{
    public class CartsController : Controller
    {
        private readonly LMSContext _context;
        public readonly ApplicationDbContext _DbContext;


        public CartsController(LMSContext context,ApplicationDbContext dbContext)
        {
            _context = context;
            _DbContext = dbContext;
        }
     
        // GET: Carts
        public async Task<IActionResult> Index()
        {
            var lMSContext = _context.carts.Include(c => c.courses).Include(c => c.student);
            return View(await lMSContext.ToListAsync());
        }

        public async Task<IActionResult> createOrder(ApplicationUser _requestData, int? id)
        {
            //Courses cr = new Courses();

            string Amount;
         
            Courses courses = _context.courses.ToList().FirstOrDefault(e => e.CourseId == id );
            Amount = courses.Price;
            decimal amt = decimal.Parse(Amount);
            Student student = _context.students.ToList().FirstOrDefault(e => e.StuId == id);


            Random randomObject = new Random();
            string transactionalId = randomObject.Next(100000, 100000).ToString();
            Razorpay.Api.RazorpayClient client = new Razorpay.Api.RazorpayClient("rzp_test_Qy5wk1RZJb8l5l", "DsTw4G8c0W0rhjrfD4MCBDjn");
            Dictionary<string, object> options = new Dictionary<string, object>();
            options.Add("amount", amt * 100);
            // options.Add("recipt", transactionalId);
            options.Add("currency", "INR");
            options.Add("payment_capture", "1");

            Razorpay.Api.Order orderResponse = client.Order.Create(options);
            string orderId = orderResponse["id"].ToString();

           
            OrderModel orderModel = new OrderModel
            {
                orderId = orderResponse.Attributes["id"],
                razorpayKey = "rzp_test_Qy5wk1RZJb8l5l",
                amount = amt * 100,
                currency = "INR",
                name = student.FirstName + student.LastName,
                email =_requestData.Email,
                contactNumber = student.PhoneNumber,
               // address = _requestData.Address,
                description = courses.Description,

            };
            _DbContext.SaveChanges();
            return View("PaymentPage", orderModel);
        }

        public class OrderModel
        {
            public string orderId { get; set; }
            public string razorpayKey { get; set; }
            public decimal amount { get; set; }
            public string currency { get; set; }

            public string name { get; set; }
            public string email { get; set; }
            public string contactNumber { get; set; }
           // public string address { get; set; }
            public string description { get; set; }
        }

        public ViewResult AfterPayment()
        {
            var paymentStatus = Request.Form["paymentstatus"].ToString();
            if (paymentStatus == "Fail")
                return View("Fail");

            var orderId = Request.Form["orderid"].ToString();
            var paymentId = Request.Form["paymentid"].ToString();
            var signature = Request.Form["signature"].ToString();

            var validSignature = CompareSignatures(orderId, paymentId, signature);
            if (validSignature)
            {
                ViewBag.Message = "Congratulations!! Your payment was successful";
                return View("Success");
            }
            else
            {
                return View("Fail");
            }
        }

        private bool CompareSignatures(string orderId, string paymentId, string razorPaySignature)
        {
            var text = orderId + "|" + paymentId;
            var secret = "DsTw4G8c0W0rhjrfD4MCBDjn";
            var generatedSignature = CalculateSHA256(text, secret);
            if (generatedSignature == razorPaySignature)
                return true;
            else
                return false;
        }

        private string CalculateSHA256(string text, string secret)
        {
            string result = "";
            var enc = Encoding.Default;
            byte[]
            baText2BeHashed = enc.GetBytes(text),
            baSalt = enc.GetBytes(secret);
            System.Security.Cryptography.HMACSHA256 hasher = new HMACSHA256(baSalt);
            byte[] baHashedText = hasher.ComputeHash(baText2BeHashed);
            result = string.Join("", baHashedText.ToList().Select(b => b.ToString("x2")).ToArray());
            return result;
        }




        public IActionResult Add_to_cart(int id)
        {

            Cart c = new Cart();
            Courses courses = _context.courses.ToList().FirstOrDefault(e=>e.CourseId == id);
           /*Student st=new Student();*/
           
            
            c.StuId = 1;
            c.CourseId = id;
            c.ImagePath = courses.ImagePath;
            c.Coursename = courses.Coursename;
            c.Price = courses.Price;
            c.Description = courses.Description;
            c.duration = courses.duration;
            c.MentorName = courses.MentorName;
            _context.carts.Add(c);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        // GET: Carts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.carts == null)
            {
                return NotFound();
            }

            var cart = await _context.carts
                .Include(c => c.courses)
                .Include(c => c.student)
                .FirstOrDefaultAsync(m => m.id == id);
            if (cart == null)
            {
                return NotFound();
            }

            return View(cart);
        }

        // GET: Carts/Create
        public IActionResult Create()
        {
            ViewData["CourseId"] = new SelectList(_context.courses, "CourseId", "CourseId");
            ViewData["StuId"] = new SelectList(_context.students, "StuId", "FirstName");
            return View();
        }

        // POST: Carts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,ImagePath,StuId,CourseId,Coursename,Price,Description,duration,MentorName")] Cart cart)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cart);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CourseId"] = new SelectList(_context.courses, "CourseId", "CourseId", cart.CourseId);
            ViewData["StuId"] = new SelectList(_context.students, "StuId", "FirstName", cart.StuId);
            return View(cart);
        }

        // GET: Carts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.carts == null)
            {
                return NotFound();
            }

            var cart = await _context.carts.FindAsync(id);
            if (cart == null)
            {
                return NotFound();
            }
            ViewData["CourseId"] = new SelectList(_context.courses, "CourseId", "CourseId", cart.CourseId);
            ViewData["StuId"] = new SelectList(_context.students, "StuId", "FirstName", cart.StuId);
            return View(cart);
        }

        // POST: Carts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,ImagePath,StuId,CourseId,Coursename,Price,Description,duration,MentorName")] Cart cart)
        {
            if (id != cart.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cart);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CartExists(cart.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CourseId"] = new SelectList(_context.courses, "CourseId", "CourseId", cart.CourseId);
            ViewData["StuId"] = new SelectList(_context.students, "StuId", "FirstName", cart.StuId);
            return View(cart);
        }

        // GET: Carts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.carts == null)
            {
                return NotFound();
            }

            var cart = await _context.carts
                .Include(c => c.courses)
                .Include(c => c.student)
                .FirstOrDefaultAsync(m => m.id == id);
            if (cart == null)
            {
                return NotFound();
            }

            return View(cart);
        }

        // POST: Carts/Delete/5
        [HttpPost, ActionName("Delete")]

LMS_GL/Controllers/FeedbacksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LMS_GL.Models;

namespace LMS_GL.Controllers
{
    public class FeedbacksController : Controller
    {
        private readonly LMSContext _context;

        public FeedbacksController(LMSContext context)
        {
            _context = context;
        }

        // GET: Feedbacks
        public async Task<IActionResult> Index()
        {
             /* return _context.feedbacks != null ? 
                          View(await _context.feedbacks.ToListAsync()) :
                          Problem("Entity set 'LMSContext.feedbacks'  is null.");*/
             return View();
        }

        

        // GET: Feedbacks/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Feedbacks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,EmailId,UserName,Suggestion")] Feedback feedback)
        {
            if (ModelState.IsValid)
            {
                _context.Add(feedback);
                await _context.SaveChangesAsync();
                TempData["success"] = "Sent Successfully";
                return RedirectToAction(nameof(Index));
            }
            return View(feedback);
        }

        



        private bool FeedbackExists(int id)
        {
          return (_context.feedbacks?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

LMS_GL/Views/Carts/Create.cshtml
@model LMS_GL.Models.Cart

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Cart</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="CourseImage" class="control-label"></label>
                <input asp-for="CourseImage" type= "file" class="form-control" />
                <span asp-validation-for="CourseImage" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="StuId" class="control-label"></label>
                <select asp-for="StuId" class ="form-control" asp-items="ViewBag.StuId"></select>
            </div>
            <div class="form-group">
                <label asp-for="CourseId" class="control-label"></label>
                <select asp-for="CourseId" class ="form-control" asp-items="ViewBag.CourseId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Coursename" class="control-label"></label>
                <input asp-for="Coursename" class="form-control" />
                <span asp-validation-for="Coursename" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="duration" class="control-label"></label>
                <input asp-for="duration" class="form-control" />
                <span asp-validation-for="duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MentorName" class="control-label"></label>
                <input asp-for="MentorName" class="form-control" />
                <span asp-validation-for="MentorName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LMS_GL/Views/Carts/Delete.cshtml
@model LMS_GL.Models.Cart

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cart</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImagePath)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.student)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.student.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.courses)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.courses.CourseId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Coursename)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Coursename)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.duration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.duration)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MentorName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MentorName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

LMS_GL/Views/Carts/Details.cshtml
@model LMS_GL.Models.Cart

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Cart</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImagePath)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.student)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.student.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.courses)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.courses.CourseId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Coursename)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Coursename)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.duration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.duration)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MentorName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MentorName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

LMS_GL/Views/Carts/Edit.cshtml
@model LMS_GL.Models.Cart

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Cart</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="ImagePath" class="control-label"></label>
                <input asp-for="ImagePath" class="form-control" />
                <span asp-validation-for="ImagePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StuId" class="control-label"></label>
                <select asp-for="StuId" class="form-control" asp-items="ViewBag.StuId"></select>
                <span asp-validation-for="StuId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CourseId" class="control-label"></label>
                <select asp-for="CourseId" class="form-control" asp-items="ViewBag.CourseId"></select>
                <span asp-validation-for="CourseId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Coursename" class="control-label"></label>
                <input asp-for="Coursename" class="form-control" />
                <span asp-validation-for="Coursename" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="duration" class="control-label"></label>
                <input asp-for="duration" class="form-control" />
                <span asp-validation-for="duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MentorName" class="control-label"></label>
                <input asp-for="MentorName" class="form-control" />
                <span asp-validation-for="MentorName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LMS_GL/Views/Carts/Fail.cshtml
@{
    ViewData["Title"] = "Fail";
}

<h1>Fail</h1>

<p>Oops! Something went wrong. Please contact helpdesk or try again later</p>

LMS_GL/Views/Carts/Index.cshtml
@model IEnumerable<LMS_GL.Models.Cart>

@{
    ViewData["Title"] = "Index";
}


             <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                <h6 class="section-title bg-white text-center text-primary px-3">Carts</h6>
                <h1 class="mb-5">Your Carts</h1>
                
            </div>


        <div class="row">
@foreach (var item in Model) {
    <div class="col-md-4 wow fadeInUp" data-wow-delay="0.1s">
                    <div class="course-item bg-light">
                        <div class="position-relative overflow-hidden">
                            <img class="img-fluid img-thumbnail" src="@item.ImagePath" style="width: 400px; height: 300px;" alt="">
                        </div>
                       
                            <h4>Course: @item.Coursename</h4>
                            <h5 class="mb-4">Price: <i class="bi bi-currency-rupee"></i>@item.Price</h5>
                            <h5 class="mb-4">Desc: @item.Description</h5>
                            <h5 class="mb-4">Duration: @item.duration</h5>
                           
               

                <div class="btn-group">
                <a asp-action="createOrder" class="btn btn-primary" asp-route-id="@item.CourseId"><i class="bi bi-bag"></i></a> 
             
                <a asp-action="Delete" class="btn btn-danger" asp-route-id="@item.id"><i class="bi bi-trash3"></i></a>
                </div>
                <div class="btn-group">
                    <a class="btn btn-info" asp-controller="Feedbacks" asp-action="Index">feedback</a>
                </div>
            </div>
            </div>
}
</div>
@*<div class="text-end">
<input />
<button>Buy Now</button>
</div>
*@





         
           
                           

LMS_GL/Views/Carts/Success.cshtml
@{
    ViewData["Title"] = "Success";
}

<h1>Success</h1>

<p>@ViewBag.Message</p>

<div>
    <a asp-controller="Home" asp-action="Index">Back to Home</a>
</div>