LMS_GL/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LMS_GL.Models;
using System.Text;
using System.Security.Cryptography;
using LMS_GL.Data;
using Microsoft.AspNetCore.Identity;

namespace LMS_GL.Controllers
{
    public class CartsController : Controller
    {
        private readonly LMSContext _context;
        public readonly ApplicationDbContext _DbContext;


        public CartsController(LMSContext context,ApplicationDbContext dbContext)
        {
            _context = context;
            _DbContext = dbContext;
        }
     
        // GET: Carts
        public async Task<IActionResult> Index()
        {
            var lMSContext = _context.carts.Include(c => c.courses).Include(c => c.student);
            return View(await lMSContext.ToListAsync());
        }

        public async Task<IActionResult> createOrder(ApplicationUser _requestData, int? id)
        {
            //Courses cr = new Courses();

            string Amount;
         
            Courses courses = _context.courses.ToList().FirstOrDefault(e => e.CourseId == id );
            Amount = courses.Price;
            decimal amt = decimal.Parse(Amount);
            Student student = _context.students.ToList().FirstOrDefault(e => e.StuId == id);


            Random randomObject = new Random();
            string transactionalId = randomObject.Next(100000, 100000).ToString();
            Razorpay.Api.RazorpayClient client = new Razorpay.Api.RazorpayClient("rzp_test_Qy5wk1RZJb8l5l", "DsTw4G8c0W0rhjrfD4MCBDjn");
            Dictionary<string, object> options = new Dictionary<string, object>();
            options.Add("amount", amt * 100);
            // options.Add("recipt", transactionalId);
            options.Add("currency", "INR");
            options.Add("payment_capture", "1");

            Razorpay.Api.Order orderResponse = client.Order.Create(options);
            string orderId = orderResponse["id"].ToString();

           
            OrderModel orderModel = new OrderModel
            {
                orderId = orderResponse.Attributes["id"],
                razorpayKey = "rzp_test_Qy5wk1RZJb8l5l",
                amount = amt * 100,
                currency = "INR",
                name = student.FirstName + student.LastName,
                email =_requestData.Email,
                contactNumber = student.PhoneNumber,
               // address = _requestData.Address,
                description = courses.Description,

            };
            _DbContext.SaveChanges();
            return View("PaymentPage", orderModel);
        }

        public class OrderModel
        {
            public string orderId { get; set; }
            public string razorpayKey { get; set; }
            public decimal amount { get; set; }
            public string currency { get; set; }

            public string name { get; set; }
            public string email { get; set; }
            public string contactNumber { get; set; }
           // public string address { get; set; }
            public string description { get; set; }
        }

        public ViewResult AfterPayment()
        {
            var paymentStatus = Request.Form["paymentstatus"].ToString();
            if (paymentStatus == "Fail")
                return View("Fail");

            var orderId = Request.Form["orderid"].ToString();
            var paymentId = Request.Form["paymentid"].ToString();
            var signature = Request.Form["signature"].ToString();

            var validSignature = CompareSignatures(orderId, paymentId, signature);
            if (validSignature)
            {
                ViewBag.Message = "Congratulations!! Your payment was successful";
                return View("Success");
            }
            else
            {
                return View("Fail");
            }
        }

        private bool CompareSignatures(string orderId, string paymentId, string razorPaySignature)
        {
            var text = orderId + "|" + paymentId;
            var secret = "DsTw4G8c0W0rhjrfD4MCBDjn";
            var generatedSignature = CalculateSHA256(text, secret);
            if (generatedSignature == razorPaySignature)
                return true;
            else
                return false;
        }

        private string CalculateSHA256(string text, string secret)
        {
            string result = "";
            var enc = Encoding.Default;
            byte[]
            baText2BeHashed = enc.GetBytes(text),
            baSalt = enc.GetBytes(secret);
            System.Security.Cryptography.HMACSHA256 hasher = new HMACSHA256(baSalt);
            byte[] baHashedText = hasher.ComputeHash(baText2BeHashed);
            result = string.Join("", baHashedText.ToList().Select(b => b.ToString("x2")).ToArray());
            return result;
        }




        public IActionResult Add_to_cart(int id)
        {

            Cart c = new Cart();
            Courses courses = _context.courses.ToList().FirstOrDefault(e=>e.CourseId == id);
           /*Student st=new Student();*/
           
            
            c.StuId = 1;
            c.CourseId = id;
            c.ImagePath = courses.ImagePath;
            c.Coursename = courses.Coursename;
            c.Price = courses.Price;
            c.Description = courses.Description;
            c.duration = courses.duration;
            c.MentorName = courses.MentorName;
            _context.carts.Add(c);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        // GET: Carts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.carts == null)
            {
                return NotFound();
            }

            var cart = await _context.carts
                .Include(c => c.courses)
                .Include(c => c.student)
                .FirstOrDefaultAsync(m => m.id == id);
            if (cart == null)
            {
                return NotFound();
            }

            return View(cart);
        }

        // GET: Carts/Create
        public IActionResult Create()
        {
            ViewData["CourseId"] = new SelectList(_context.courses, "CourseId", "CourseId");
            ViewData["StuId"] = new SelectList(_context.students, "StuId", "FirstName");
            return View();
        }

        // POST: Carts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,ImagePath,StuId,CourseId,Coursename,Price,Description,duration,MentorName")] Cart cart)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cart);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CourseId"] = new SelectList(_context.courses, "CourseId", "CourseId", cart.CourseId);
            ViewData["StuId"] = new SelectList(_context.students, "StuId", "FirstName", cart.StuId);
            return View(cart);
        }

        // GET: Carts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.carts == null)
            {
                return NotFound();
            }

            var cart = await _context.carts.FindAsync(id);
            if (cart == null)
            {
                return NotFound();
            }
            ViewData["CourseId"] = new SelectList(_context.courses, "CourseId", "CourseId", cart.CourseId);
            ViewData["StuId"] = new SelectList(_context.students, "StuId", "FirstName", cart.StuId);
            return View(cart);
        }

        // POST: Carts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,ImagePath,StuId,CourseId,Coursename,Price,Description,duration,MentorName")] Cart cart)
        {
            if (id != cart.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cart);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CartExists(cart.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CourseId"] = new SelectList(_context.courses, "CourseId", "CourseId", cart.CourseId);
            ViewData["StuId"] = new SelectList(_context.students, "StuId", "FirstName", cart.StuId);
            return View(cart);
        }

        // GET: Carts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.carts == null)
            {
                return NotFound();
            }

            var cart = await _context.carts
                .Include(c => c.courses)
                .Include(c => c.student)
                .FirstOrDefaultAsync(m => m.id == id);
            if (cart == null)
            {
                return NotFound();
            }

            return View(cart);
        }

        // POST: Carts/Delete/5
        [HttpPost, ActionName("Delete")]

LMS_GL/Controllers/ContactUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LMS_GL.Models;

namespace LMS_GL.Controllers
{
    public class ContactUsController : Controller
    {
        private readonly LMSContext _context;

        public ContactUsController(LMSContext context)
        {
            _context = context;
        }

        // GET: ContactUs
        public async Task<IActionResult> Index()
        {
            /*var lMSContext = _context.contactUs.Include(c => c.student);
            return View(await lMSContext.ToListAsync());*/
            return View();
        }



        // GET: ContactUs/Create
        public IActionResult Create()
        {
           /* ViewData["StuId"] = new SelectList(_context.students, "StuId", "FirstName");*/

            return View();
        }

        // POST: ContactUs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("StuId,Name,GmailId,PhoneNumber,Message")] ContactUs contactUs)
        {
           
                _context.Add(contactUs);
                await _context.SaveChangesAsync();
            TempData["success"] = "Message Sent Successfully";
            return RedirectToAction(nameof(Index));
        }

        private bool ContactUsExists(string id)
        {
          return (_context.contactUs?.Any(e => e.Name == id)).GetValueOrDefault();
        }
    }
}

LMS_GL/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LMS_GL.Models;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;
using Microsoft.AspNetCore.Authorization;

namespace LMS_GL.Controllers
{
    public class CoursesController : Controller
    {
        public readonly LMSContext _context;
        public IHostingEnvironment _env;

        public CoursesController(LMSContext context, IHostingEnvironment env)
        {
            _context = context;
            _env = env;
        }
        

        // GET: Courses
        public async Task<IActionResult> Index()
        {
            var lMSContext = _context.courses.Include(c => c.category);
            return View(await lMSContext.ToListAsync());
            //return View();
        }
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> AdminIndex()
        {
            var lMSContext = _context.courses.Include(c => c.category);
            return View(await lMSContext.ToListAsync());
            //return View();
        }


        // GET: Courses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.courses == null)
            {
                return NotFound();
            }

            var courses = await _context.courses
                .Include(c => c.category)
                .FirstOrDefaultAsync(m => m.CourseId == id);
            if (courses == null)
            {
                return NotFound();
            }

            return View(courses);
        }

        // GET: Courses/Create
        public IActionResult Create()
        {
            ViewData["CategId"] = new SelectList(_context.category, "CategId", "CategoryName");
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( Courses courses)
        {
            var nam = Path.Combine(_env.WebRootPath + "/Images", Path.GetFileName(courses.CourseImage.FileName));
            courses.CourseImage.CopyTo(new FileStream(nam, FileMode.Create));
            courses.ImagePath= "Images/" + courses.CourseImage.FileName;
            _context.Add(courses);
                await _context.SaveChangesAsync();
            TempData["success"] = "Course Created Successfully";
            return RedirectToAction(nameof(Index));
            
            ViewData["CategId"] = new SelectList(_context.category, "CategId", "CategoryName", courses.CategId);
            return View(courses);
        }

        // GET: Courses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.courses == null)
            {
                return NotFound();
            }

            var courses = await _context.courses.FindAsync(id);
            if (courses == null)
            {
                return NotFound();
            }
            ViewData["CategId"] = new SelectList(_context.category, "CategId", "CategoryName", courses.CategId);
            return View(courses);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Courses courses)
        {
            if (id != courses.CourseId)
            {
                return NotFound();
            }
                    var nam = Path.Combine(_env.WebRootPath + "/Images", Path.GetFileName(courses.CourseImage.FileName));
                    courses.CourseImage.CopyTo(new FileStream(nam, FileMode.Create));
                    courses.ImagePath = "Images/" + courses.CourseImage.FileName;
                    _context.Update(courses);
                    await _context.SaveChangesAsync();
            TempData["success"] = "Course Edited Successfully";
            return RedirectToAction(nameof(Index));
        }

        // GET: Courses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.courses == null)
            {
                return NotFound();
            }

            var courses = await _context.courses
                .Include(c => c.category)
                .FirstOrDefaultAsync(m => m.CourseId == id);
            if (courses == null)
            {
                return NotFound();
            }

            return View(courses);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.courses == null)
            {
                return Problem("Entity set 'LMSContext.courses'  is null.");
            }
            var courses = await _context.courses.FindAsync(id);
            if (courses != null)
            {
                _context.courses.Remove(courses);
            }
            
            await _context.SaveChangesAsync();
            TempData["success"] = "Category Deleted Successfully";
            return RedirectToAction(nameof(Index));
        }


        private bool CoursesExists(int id)
        {
          return (_context.courses?.Any(e => e.CourseId == id)).GetValueOrDefault();
        }
    }
}

LMS_GL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>eLEARNING - Academia</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/css/nice-select.min.css" integrity="sha512-CruCP+TD3yXzlvvijET8wV5WxxEh5H8P4cmz0RFbKK6FlZ2sYl3AEsKlLPHbniXKSrDdFewhbmBK5skbdsASbQ==" crossorigin="anonymous" />
     <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css"/>
     <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"/>

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="lib/animate/animate.min.css" rel="stylesheet">
    <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="/css/style.css" rel="stylesheet">
</head>

 <body style="background-color:aliceblue">
 <!------------------------------------------------------------- Navbar Start ----------------------------------------------------->
    <nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
        <a asp-controller="Home" asp-action="Index" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
            <h2 class="m-0 text-primary"><i class="bi bi-vector-pen"></i>Academia</h2>
        </a>
        <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto p-4 p-lg-0">
                <a class="nav-item nav-link active" asp-controller="Home" asp-action="Index">Home</a>
               <div class="nav-item dropdown">
                    <a aasp-controller="Categories" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Category</a>
                    <div class="dropdown-menu fade-down m-0">
                        <a asp-controller="Categories" asp-action="Adminindex" title="owner" class="dropdown-item">Admin</a>
                        <a asp-controller="Categories" asp-action="Index" title="user" class="dropdown-item">Student</a>
                    </div>
                </div>
                <div class="nav-item dropdown">
                    <a asp-controller="Courses" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Courses</a>
                    <div class="dropdown-menu fade-down m-0">
                        <a asp-controller="Courses" asp-action="Adminindex" title="owner" class="dropdown-item">Admin</a>
                        <a asp-controller="Courses" asp-action="Index" title="user" class="dropdown-item">Student</a>
                    </div>
                </div>
                <div class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                    <div class="dropdown-menu fade-down m-0">
                        <a asp-controller="Home" asp-action="About" title="info" class="dropdown-item">About</a>
                        <a asp-controller="Home" asp-action="OurTeam" class="dropdown-item">Our Team</a>
                        <a asp-controller="Home" asp-action="Privacy" class="dropdown-item">Privacy Policy</a>
                    </div>
                </div>
                <a class="nav-item nav-link" asp-controller="ContactUs" title="connect" asp-action="Index">ContactUs</a>
                <a class="nav-item nav-link" asp-controller="Feedbacks" title="Suggestions" asp-action="Index" >Feedbacks</a>
                
                @if (User.Identity.IsAuthenticated)
                {
                    <a class="nav-item nav-link" asp-controller="Carts" title="View Cart" asp-action="Index"><i class="bi bi-cart4" style="width:100px"></i></a>
                }
            </div>
            <div class="btn-group" role="group">
                <partial name="_LoginPartial" />   
            </div>
        </div>
    </nav>
<!----------------------------------------------------------- Navbar End ------------------------------------------------------------->
<div class="container mw-100">
        <main role="main" class="pb-3">
            <div class="align-content-center bg-black">
                <partial name="_Notification"></partial>
            </div>
            @RenderBody()
        </main>
    </div>
<!--------------------------------------------------------- Footer Start --------------------------------------------------------------->
<div class="container-fluid bg-dark text-light footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
<div class="container py-5">
    <div class="row g-6">
        <div class="col-lg-3 col-md-6">
            <h4 class="text-white mb-3">More</h4>
            <a class="btn btn-link" asp-controller="Home" asp-action="About">About Us</a>
            <a class="btn btn-link" asp-controller="ContactUs" asp-action="Index">Contact Us</a>
            <a class="btn btn-link" asp-controller="Home" asp-action="Privacy">Privacy Policy</a>
        </div>
        <div class="col-lg-3 col-md-6">
            <h4 class="text-white mb-3">Contact</h4>
            <a href="https://goo.gl/maps/nwD3gy8TfxJVKMTr6">
                <p class="text-white mb-2"><i class="fa fa-map-marker-alt me-3"></i>Academia, New Delhi, INDIA</p>
            </a>
            <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
            <a href="https://mail.google.com/mail/?view=cm&fs=1&to=someone@example.com&su=SUBJECT&body=BODY&bcc=someone.else@example.com">
            <p class="text-white mb-2"><i class="fa fa-envelope me-3"></i>AcademiaInfo@gmail.com</p>
            </a>
            <div class="d-flex pt-2">
                <a class="btn btn-outline-light btn-social" href="https://www.facebook.com/"><i class="fab fa-facebook-f"></i></a>
                <a class="btn btn-outline-light btn-social" href="https://www.youtube.com/"><i class="fab fa-youtube"></i></a>
                <a class="btn btn-outline-light btn-social" href="https://in.linkedin.com/"><i class="fab fa-linkedin-in"></i></a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <h4 class="text-white mb-3">Download</h4>
            <div class="d-flex  pt-2">
                <a class="btn btn-outline-light btn-social" href="https://play.google.com/store/games?utm_source=apac_med&utm_medium=hasem&utm_content=Oct0121&utm_campaign=Evergreen&pcampaignid=MKT-EDR-apac-in-1003227-med-hasem-py-Evergreen-Oct0121-Text_Search_BKWS-BKWS%7CONSEM_kwid_43700065205026385_creativeid_535350509687_device_c&gclid=CjwKCAjwu5yYBhAjEiwAKXk_eHUr98-BoVzIJH4yRoPhRbJ6aIoWVIZMJrXSNISnkUOerJaPioMiNRoCY_0QAvD_BwE&gclsrc=aw.ds"><i class="bi bi-google-play"></i></a>
                <a class="btn btn-outline-light btn-social" href="https://www.apple.com/in/app-store/"><i class="bi bi-apple"></i></a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <h4 class="text-white mb-3">Newsletter</h4>
            <p>SignUp to Our NewsLetter to know us more</p>
            <div class="position-relative mx-auto" style="max-width: 400px;">
                <input class="form-control border-0 w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
                <a href="#" type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</a>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="copyright">
        <div class="row">
            <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                &copy; <a class="border-bottom" asp-controller="Home" asp-action="Index">Academia</a>, All Right Reserved.
            </div>
            <div class="col-md-6 text-center text-md-end">
                <div class="footer-menu">
                    <a asp-controller="Home" asp-action="Index">Home</a>
                    <a asp-controller="ContactUs" asp-action="Index">Help</a>
                    <a href="">Cookies</a>
                    <a asp-controller="Feedbacks" asp-action="Index">FAQs</a>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
<!-- Footer End -->


<!-- Back to Top -->

<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
@*<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>*@
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
<script src="lib/wow/wow.min.js"></script>
<script src="lib/easing/easing.min.js"></script>
<script src="lib/waypoints/waypoints.min.js"></script>
<script src="lib/owlcarousel/owl.carousel.min.js"></script>

<!-- Template Javascript -->
<script src="js/main.js"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>

</html>

LMS_GL/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["Success"]');    
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["Error"]');    
    </script>
}